name: CD

on:
  workflow_run:
    types: [completed]
    workflows: [CI]
    branches: [main]

permissions:
  contents: read
  packages: write

env:
  BASE_IMAGE_TAG: ghcr.io/${{ github.repository_owner }}/act-testing-mcp:latest
  ACT_VERSION: "0.2.82"

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build and Push Multi-Arch Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read MCP metadata
        id: mcp-metadata
        run: echo "metadata<<EOF" >> $GITHUB_OUTPUT && cat mcp-metadata.yaml >> $GITHUB_OUTPUT && echo "EOF" >> $GITHUB_OUTPUT

      - uses: docker/build-push-action@v6
        with:
          pull: true
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ env.BASE_IMAGE_TAG }}
          build-args: |
            ACT_VERSION=${{ env.ACT_VERSION }}
            MCP_METADATA=${{ steps.mcp-metadata.outputs.metadata }}
          cache-from: |
            type=gha
          cache-to: |
            type=gha,mode=max
