name: Docker MCP Gateway Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-docker-gateway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t act-testing-mcp:${{ github.sha }} .

      - name: Verify act installed
        run: docker run --rm --entrypoint act act-testing-mcp:${{ github.sha }} --version

      - name: Smoke test Node
        run: docker run --rm act-testing-mcp:${{ github.sha }} node -e "console.log('ok')"

      - name: Push Docker image
        if: github.event_name != 'pull_request'
        run: |
          docker tag act-testing-mcp:${{ github.sha }} garthdb/act-testing-mcp:latest
          docker push garthdb/act-testing-mcp:latest

      - name: Optional: Gateway test
        continue-on-error: true
        run: |
          if docker extension list | grep -q mcp-gateway; then
            docker mcp gateway run --servers docker://garthdb/act-testing-mcp:latest --test-timeout 60s
          else
            echo "Gateway extension unavailable in runner"
          fi
